//Autoclose thurnouts based on non automations

//Southbound trains
//scenic track A

//Track A -> B
AUTOSTART SEQUENCE(140)
    AT(BD_S5_B)
    IFTHROWN(UFM_T2_A__UGS_T3_E)
        CLOSE(9004)
    ENDIF
FOLLOW(140)

// Track B->A
AUTOSTART SEQUENCE(141)
    AT(BD_S6_A)
    IFTHROWN(UGS_T4_A__UMF_T3_E)
        CLOSE(9007)
    ENDIF
FOLLOW(141)

//Track D->A
AUTOSTART SEQUENCE(142)
    AT(BD_S6_A)
    IFTHROWN(UGS_T4_A__UMF_T3_E)
        CLOSE(9009)
    ENDIF 
FOLLOW(142)

//Track D->B
AUTOSTART SEQUENCE(143)
    AT(BD_S6_B)
    IFTHROWN(DMF_T3_E__UFM_T4_A)
        CLOSE(9008)
    ENDIF 
FOLLOW(143)

AUTOSTART SEQUENCE(144)
    AT(BD_S6_B) 
    IFTHROWN(UFM_T5_A__UMF_T3_E)
        CLOSE(9010)
    ENDIF
FOLLOW(144)

