//Test turnout sequence
 #define turnoutTest \
  turnTest(UGS_T1_H) \ AA
  turnTest(DFM_T1_A__DFM_T2_E) \  EA
  turnTest(UGS_T2_E__DFM_T1_A) \ AB
  turnTest(UFM_T1_A__UGS_T2_E) \ BA
  turnTest(DMF_T1_E__UMF_T1_A) \ CA
  turntest(UMF_T1_A__DMF_T1_E) \ DA  
  turnTest(DGS_T3_E__DFM) \ EC
  turnTest(DGS_T1_A__HS_T2_E) \ FA
  turntest(UGS_T3_A__UFM_T3_E) \ AC
  turnTest(UFM_T2_E__DMF_T2_A) \ BB
  turntest(DMF_T2_E__UGS_T1_A) \ BC
  turnTest(DMF_T3_A__DMF_T1_E) \ BD
  turnTest(DMF_T2_A__DMF_T1_E) \ CB
  turntest(DMF_T3_E__DFM_T1_A) \ CC
  turnTest(UMF_T2_E__UFM_T1_A) \ DB
  turnTest(DFM_T4_A__DFMT3_E) \ ED
  turnTest(DGS_T2_A__HS_T3_A) \ FB
  turnTest(HS_T1_A__HS_T2_E) \ HA
  turnTest(HS_T2_A__HS_T3_E) \ HB
  turnTest(UGS_T4_E__UFM_T5_A) \ AD
  turntest(UFM_T5_E__UMF_T3_A) \ BF
  turnTest(UFM_T5_E__UMF_T3A_A) \ BF-A
  turnTest(UFM_T3_E__UMF_T2_A) \ DC
  turnTest(DGS_T3_A__DFM_T2_E) \ FC
  turnTest(HS_T3) \ HC
  turntest(HS_T4_E__HS_T5_A) \ HD
  turnTest(HS_T5_A__HS_T6) \ HE
  turntest(HS_T6) \ HF
  turnTest(DGS_T4_A__DFM_T5_E) \ FD
  

  // rear boards
  turntest(UFM_T6_A__UGS_T5_E) \ BG
  turnTest(DFM_T5_E__DGS_T4_A) \ EE
  turntest(UMF_T7_E__UMF_T8_A) \ BH
  turnTest(UFM_T8_E__UMF_T9_A) \ BI
  turnTest(UMF_T9_E__UMF_T10_A) \ BJ
  turnTest(UMF_T10) \ BK
  turntest(DFM_T7_E) \ EG
  turnTest(DFM_T8_E__DFM_T7_A) \ EH
  turntest(DFM_T9_E__DFM_T8_A) \ EI
  turnTest(DFM_T10_E__DFM_T9_A) \ EJ
  turnTest(UMF_T11_E__UMF_T12_A) \ BL
  turnTest(UMF_T12_E__UMF_T13_A) \ BM
  turntest(UMF_T13_E__UMF_T14_A) \ BN
  turntest(UMF_T14_E) \ BO
  turnTest(DMF_T5_E__DMF_T6_A) \ CE
  turntest(DMF_T6_E__DMF_T7_A) \ CF
  turnTest(DMF_T7) \ CG
  turntest(UFM_T4_E__UMF_T5_A) \ DD
  turnTest(UFM_T5_E__UMF_T6_A) \ DE
  turntest(UFM_T6_E__UGS_T7_A) \ DF
  turnTest(UFM_T7) \ DG
  turnTest(DFM_T11) \ EK
  turnTest(DFM_T12_E__DFM_T11) \ EL
  turnTest(DFM_T13_E__DFM_T12_A) \ EM
  turntest(DFM_T14_E__DFM_T13_A) \ EN
  turnTest(UGS_T6_A__FYUG_T10_E)\ AF
  turntest(UMF_T15_E__UGS_T6_A) \ BP
  turntest(DFM_T15_A__DGS_T6_E) \ EO
  turnTest(DGS_T6_E__DFM_T15_A) \ FF
  turntest(DMF_T8_E__DMT_T9_A) \ CH
  turnTest(DMF_T9_E__DMT_T10_A) \ CI
  turnTest(DMF_T10_E__DMT_T11_A) \ CJ
  turnTest(UMF_T8_E__UMF_T9_A) \ DH
  turnTest(UFM_T9_E__UFM_T10_A) \ DI
  turnTest(UFM_T10_E__UFM_T11_A) \ DJ
  turnTest(UFM_T11) \ DK 
  turnoutReset \
  myLCDOutput(turnouts)