/* mySensors.h
*
* Kept now on github https://github.com/BMRG-Holgat/Config-Files.git
*
* Define Sensors and Aliases
*
* ALIAS(Sensor_name, pin#)
* Sensor_name(Board#_{IR|BD}_Track)
* 
* Verson 0.1
*
* Version 1
* Updated sensor syntax
*
*/

//==============================================================
//
// FIX ALL SENSOR VALUES
//
//==============================================================

//Track A Up goods slow
ALIAS(B1_IR_A,322)
ALIAS(B3_IR_A,482)
ALIAS(B5_IR_A,576)
ALIAS(B7_IR_A,721)
ALIAS(B9_IR_A,828)


ALIAS(B5_IR_B1_E,573)
ALIAS(B5_IR_B2_E,577)
ALIAS(B5_IR_B3_E,585)
ALIAS(B5_IR_C1_E,575)
ALIAS(B5_IR_C2_E,567)
ALIAS(B5_IR_C3_E,583)
ALIAS(B5_IR_C4_E,579)
ALIAS(B5_IR_C5_E,571)




//Track A Up goods slow
ALIAS(UGS_B1_A1)
ALIAS(SNS1_MAIN_TRN1_APP)
ALIAS(UGS_SNS_STN)
ALIAS(UGS_Head_End)
ALIAS(SNS2_MAIN_TRN1_EX)
ALIAS(SNS3_STN)
ALIAS(SNS4_MAIN_TRN2_APP)
ALIAS(SNS5_STN_TRN2_APP)
ALIAS(SNS6_TRN2_STN_EX)
ALIAS(SNS7_MAIN_TRN3_APP)
//ALIAS(UGS_SNS_12,340)
//ALIAS(UGS_SNS_11,245)
//ALIAS(UGS_SNS_10,246)
ALIAS(UGS_B9_A1)
ALIAS(UGS_SNS_10)
ALIAS(UGS_SNS_11)
ALIAS(UGS_SNS_12)



// Track B Up Fast Mixed
ALIAS(SNS_FB_T1_E)
ALIAS(SNS_FB_T1_A)
ALIAS(SNS_FB_T2_E)
ALIAS(SNS_FB_T2_A)
ALIAS(SNS_FB_T3_E)
ALIAS(SNS_FB_T3_A)
ALIAS(SNS_FB_T4_E)
ALIAS(SNS_FB_T4_A)
ALIAS(SNS_FB_T5_E)
ALIAS(SNS_FB_T5_A)

// Track C Down Main Fast
ALIAS(SNS_DFM_B1,319)

// Track D Up Main Fast
ALIAS(SNS_UFM_B1,318)


// Track E Down Fast Mixed
ALIAS(SNS_DFM_STN_1,320)
ALIAS(SNS_DFM_BYPASS_1,321)

// Track F Down Slow Goods


// Track G Holgate Sidings

//Fiddle yard A 

// Fiddle yard B
ALIAS(FYB_SNS1_T1_F)
ALIAS(FYB_SNS2_T1_M)
ALIAS(FYB_SNS1_T2_F)
ALIAS(FYB_SNS2_T2_M)
ALIAS(FYB_SNS1_T3_F)
ALIAS(FYB_SNS2_T3_M)
ALIAS(FYB_SNS1_T4_F)
ALIAS(FYB_SNS2_T4_M)
ALIAS(FYB_SNS1_T5_F)
ALIAS(FYB_SNS2_T5_M)

//Fiddle yard C
ALIAS(FYC_SNS1_T1_F)
ALIAS(FYC_SNS2_T1_M)
ALIAS(FYC_SNS1_T2_F)
ALIAS(FYC_SNS2_T2_M)
ALIAS(FYC_SNS1_T3_F)
ALIAS(FYC_SNS2_T3_M)
ALIAS(FYC_SNS1_T4_F)
ALIAS(FYC_SNS2_T4_M)
ALIAS(FYC_SNS1_T5_F)
ALIAS(FYC_SNS2_T5_M)

//Fiddle yard D
ALIAS(FYD_SNS1_T1_F,420)
ALIAS(FYD_SNS2_T1_M,545)
ALIAS(FYD_SNS1_T2_F,418)
ALIAS(FYD_SNS2_T2_M)
ALIAS(FYD_SNS1_T3_F,419)
ALIAS(FYD_SNS2_T3_M)
ALIAS(FYD_SNS1_T4_F)
ALIAS(FYD_SNS2_T4_M)
ALIAS(FYD_SNS1_T5_F)
ALIAS(FYD_SNS2_T5_M)

//Fiddle yard E
ALIAS(FYE_SNS1_T1_F)
ALIAS(FYE_SNS2_T1_M)
ALIAS(FYE_SNS1_T2_F)
ALIAS(FYE_SNS2_T2_M)
ALIAS(FYE_SNS1_T3_F)
ALIAS(FYE_SNS2_T3_M)
ALIAS(FYE_SNS1_T4_F)
ALIAS(FYE_SNS2_T4_M)
ALIAS(FYE_SNS1_T5_F)
ALIAS(FYE_SNS2_T5_M)

//Fiddle yard F
ALIAS(DSG_SNS_9)
ALIAS(DSG_SNS_10)
ALIAS(DSG_SNS_11)
ALIAS(DSG_SNS_12)