/* mySensors.h
*
* Define Sensors and Aliases
*
* ALIAS(Sensor_name, pin#)
* 
* Verson 0.1
*/

//Track A Up goods slow
ALIAS(SNS1_TRN1_APP, 24)
ALIAS(SNS2_MAIN_TRN1_EX, 25)
ALIAS(SNS3_STN, 26)
ALIAS(SNS4_MAIN_TRN2_APP, 27)
ALIAS(SNS5_STN_TRN2_APP, 28)
ALIAS(SNS6_TRN2_EX, 29)

// Track B Up Fast Mixed


// Track C Down Main Fast


// Track D Up Main Fast


// Track E Down Fast Mixed


// Track F Down Slow Goods


// Track G Holgate Sidings

//Fiddle yard A 

// Fiddle yard B
ALIAS(FYB_SNS1_T1_F)
ALIAS(FYB_SNS2_T1_M)
ALIAS(FYB_SNS1_T2_F)
ALIAS(FYB_SNS2_T2_M)
ALIAS(FYB_SNS1_T3_F)
ALIAS(FYB_SNS2_T3_M)
ALIAS(FYB_SNS1_T4_F)
ALIAS(FYB_SNS2_T4_M)
ALIAS(FYB_SNS1_T5_F)
ALIAS(FYB_SNS2_T5_M)

//Fiddle yard C
ALIAS(FYC_SNS1_T1_F)
ALIAS(FYC_SNS2_T1_M)
ALIAS(FYC_SNS1_T2_F)
ALIAS(FYC_SNS2_T2_M)
ALIAS(FYC_SNS1_T3_F)
ALIAS(FYC_SNS2_T3_M)
ALIAS(FYC_SNS1_T4_F)
ALIAS(FYC_SNS2_T4_M)
ALIAS(FYC_SNS1_T5_F)
ALIAS(FYC_SNS2_T5_M)

//Fiddle yard D
ALIAS(FYD_SNS1_T1_F)
ALIAS(FYD_SNS2_T1_M)
ALIAS(FYD_SNS1_T2_F)
ALIAS(FYD_SNS2_T2_M)
ALIAS(FYD_SNS1_T3_F)
ALIAS(FYD_SNS2_T3_M)
ALIAS(FYD_SNS1_T4_F)
ALIAS(FYD_SNS2_T4_M)
ALIAS(FYD_SNS1_T5_F)
ALIAS(FYD_SNS2_T5_M)

//Fiddle yard E
ALIAS(FYE_SNS1_T1_F)
ALIAS(FYE_SNS2_T1_M)
ALIAS(FYE_SNS1_T2_F)
ALIAS(FYE_SNS2_T2_M)
ALIAS(FYE_SNS1_T3_F)
ALIAS(FYE_SNS2_T3_M)
ALIAS(FYE_SNS1_T4_F)
ALIAS(FYE_SNS2_T4_M)
ALIAS(FYE_SNS1_T5_F)
ALIAS(FYE_SNS2_T5_M)

//Fiddle yard F
