/* 
* Holgate sidings
*/

SEQUENCE(700)
IFNOT(CD_S4_HA)
    RESERVE(H_T1)
    CLOSE(9019)
    FWD(20)
    AT(CD_S4_HA) ESTOP
    STASH(CD_S4_HA)
    IFTHROWN(9030)
        CLOSE(9030)
        FREE(E_B1)
        GREEN(SIG_E4)
    ENDIF
    CLOSE(9031)
    GREEN(SIG_F4)
    RETURN
ENDIF 
IFNOT(CD_S4_HB) 
    RESERVE(H_T2)
    THROW(9019)
    FWD(20) 
    AT(CD_S4_HB) ESTOP
    STASH(CD_S4_HB)
    IFTHROWN(9030)
        CLOSE(9030)
        FREE(E_B1)
        GREEN(SIG_E4)
    ENDIF
    CLOSE(9031)
    GREEN(SIG_F4)
    RETURN
ENDIF 
IFNOT(CD_S4_HC) 
    RESERVE(H_T3)
    THROW(9017)
    FWD(20) 
    AT(CD_S4_HC) ESTOP
    STASH(CD_S4_HC)
    IFTHROWN(9030)
        CLOSE(9030)
        FREE(E_B1)
        GREEN(SIG_E4)
    ENDIF
    CLOSE(9031)
    GREEN(SIG_F4)
    RETURN
ENDIF 
IFNOT(CD_S4_HD) 
    RESERVE(H_T4)
    THROW(9016)
    FWD(20) 
    AT(CD_S4_HD) ESTOP
    STASH(CD_S4_HD)
    IFTHROWN(9030)
        CLOSE(9030)
        FREE(E_B1)
        GREEN(SIG_E4)
    ENDIF
    CLOSE(9031)
    GREEN(SIG_F4)
    RETURN
ENDIF
DONE
