/* myRoster.h
*
* Kept now on github https://github.com/BMRG-Holgat/Config-Files.git
*
* Define Roster locos
*
* ROSTER(dcc-addr,desc,functions{},...)
*
* WARNING
* Duplicats cannot be included in this file
*/
//Define locos that can be used on this layout
ROSTER(4052,"Class 40","Lights")
ROSTER(5703,"Freightliner 03","")
ROSTER(4750,"Freightliner 50","")
ROSTER(2210,"Voyager","Lights")
ROSTER(2209,"Voyager","Lights")
ROSTER(5004,"3car Dmu","Lights")
//ROSTER(1083,"Dmu","Lights/Sound/*Horn/*Brakes/*Release////Sound/*Doors/*D Horn")
ROSTER(5359,"108-DMU","Lights/Sound/*Horn 1/*Horn 2/*Door Slam/*Air Buildup/*Couple/*Uncouple/Brake/*Flange/Rail Joint/*guard Whistle/Coast///*Uncouple Cycle")
ROSTER(6631,"Thomas Moore","Lights//Empty/Forward/Reverse")
ROSTER(2604,"Coal","Lights//Rear")
ROSTER(89,"Azuma-89","Lights/Sound/*High Horn/*Low Horn/*Doors/*Brake/*Driver Door/*Compresser/Diesel/Speed Squeal/*Whistle/*Guard-Driver//*Sanders/*Nose Open/*Nose Close/*Announcement/*Speed detonators")
ROSTER(90,"Azuma-90","Lights/Sound/*High Horn/*Low Horn/*Doors/*Brake/*Driver Door/*Compresser/Diesel/Speed Squeal/*Whistle/*Guard-Driver//*Sanders/*Nose Open/*Nose Close/*Announcement/*Speed detonators")

//Arthurs locos
ROSTER(2491,"Class 24 97201","Lights/Sound/*Double Horn/*Single Horn/*Brake Release/Flange Squeal/*Door slam/Compressor OFF/*Volume/Inertia/*Air release/*Buffering up/Spirax Valves/Tail Lights")
ROSTER(5804,"58004 Coal","Lights/Sound/Active Brake/*Horn 1/*Horn 2/Tail lights/Notch up/*Brake release/*Guard Whistle/*Cab Beep/Rail Echo/Cab Light/*Announcement/Flange Squeal 1/Flange Squeal 2/*Comms Bell/*Horn 3/*Horn 4/Mute/Shunting")
ROSTER(8009,"Azuma 9 Car","Lights/Sound/*Horn Short/*Horn Medium/*Horn Long/*Guard Whistle///Electric/Notch Up/SPEED LOCK/Flange Squeal/*Pass By/*Door Beeps/*Brake Release/*Pantograph/*Coupling Up/Compressor/*Announce 1/*Announce 2/*Announce 3/Station Sound")
ROSTER(9905,"JAMES","//Sounds/ACTIVE BRAKE/*Whistle 1/*Whistle 2/Blower/Coal Shovelling/*Thomas Tune/*James Tune/*Guard Whistle/Blower 2/*Buffer Up/*Water Hatch/*Cinders and Ashes/Flange Squeal/Coach Rattle/*Doors Closing/*Dump Down/*Whistle 3/*Wheel Slip/SHUNT")
ROSTER(818,"08818 Blue","/Sound/*Brake sound/*Horn Single/*Horn Double/Cold Start/Engine Idle/Speed Lock/Exhauster/Flange Squeal/*Guard Whistle/*Buffer Clash/*Coupling/Compressor/*Sanding/Handbrake/Fuel Pump/*Wagon Buffering/Cab door/Mute/*Draw up")
ROSTER(8560,"D8560 Green","Lights/Sound/Active Brake/*Horn 1/*Horn 2/Clag 2/Light off #1/Notch up/*Rev up 2/*Guard Whistle/Gas Off/*Apply Brake/Light off #2/Flange Squeal/*Buffering up/*Clag passing/*Horn 3/*Rev Rattle/*Horn 4/MUTE/SHUNT")
ROSTER(2032,"20132 Railfreight","Lights/Sound/Active Brake/*Horn 1/*Horn 2/*Clag 2/Tail Lights/*Notch Up/*Brake Release/*Guard Whistle/Rail Echo/*Air Release/Cab Light/*Level Crossing/Motion Sounds/Truck Squeal/*Coupling Up/*Set off 2/*Horn 3/MUTE/SHUNT")
ROSTER(2048,"20048 Blue","Lights/Sound/Active Brake/*Horn 1/*Horn 2/*Clag 2/Tail Lights/*Notch Up/*Brake Release/*Guard Whistle/Rail Echo/*Air Release/Cab Light/*Level Crossing/Motion Sounds/Truck Squeal/*Coupling Up/*Set off 2/*Horn 3/MUTE/SHUNT")
ROSTER(2056,"20156 Railfreight","Lights/Sound/Active Brake/*Horn 1/*Horn 2/*Clag 2/Tail Lights/*Notch Up/*Brake Release/*Guard Whistle/Rail Echo/*Air Release/Cab Light/*Level Crossing/Motion Sounds/Truck Squeal/*Coupling Up/*Set off 2/*Horn 3/MUTE/SHUNT")
ROSTER(2063,"20063 Blue","Lights/Sound/Active Brake/*Horn 1/*Horn 2/*Clag 2/Tail Lights/*Notch Up/*Brake Release/*Guard Whistle/Rail Echo/*Air Release/Cab Light/*Level Crossing/Motion Sounds/Truck Squeal/*Coupling Up/*Set off 2/*Horn 3/MUTE/SHUNT")
ROSTER(2096,"20906 Hunslet","Lights/Sound/*Horn high/*Horn Low/*Horn Double/Power/*Drive brake/*Brake Release/*Guard Whistle/Flange Squeal/*Buffering up/*Buffer Clash/*Coach Door/*Sanding valve/*Auto uncouple/SHUNT/Spirax Valve//Tail Light//Parking")
ROSTER(3131,"31131 Blue","Lights/Sound/*BRAKE/*Single Horn/*Double Horn/Light Engine/Engine Idle/SPEED LOCK/*Cold Start/Flange Squeal/*Guards Whistle/*Buffering Up/*Coupling Up/Compressor/Spirax Valves/Cooling Fan/Primer Pump/*Auto Wagon Buffering/Drivers Door/MUTE SOUNDS/Lights Off End 1")
ROSTER(3154,"31154 Railfreight","Lights/Sound/*BRAKE/*Single Horn/*Double Horn/Light Engine/Engine Idle/SPEED LOCK/*Cold Start/Flange Squeal/*Guards Whistle/*Buffering Up/*Coupling Up/Compressor/Spirax Valves/Cooling Fan/Primer Pump/*Auto Wagon Buffering/Drivers Door/MUTE SOUNDS/Lights Off End 1")
ROSTER(3706,"37406 Speedlink","Lights/Sound/ACTIVE BRAKING/*Horn 1/*Horn 3/*Clag/TAIL LIGHTS/*Notch Up/*Prepare for Off/*Guard’s Whistle/Spirax/*Brake Release///Squeal 1/Squeal 2/*Rev Up/Compressor/*Clag 2/*Horn 2/MUTE/SHUNT")
ROSTER(3727,"37027 LL Blue","Lights/Sound/*Horn High-Low/*Horn Low-High/*Brake Squeal/*Notch Up/*Notch Down/*Idle/Thrash/*Cold Start/Compressor/*Door Slam/Cooling Fan/*Horn Long High/*Horn Long Low/Primer Pump/Flange Squeal/Spirax Valves/*Horn Short Low/*Horn Short High/*Buffering")
ROSTER(3739,"37239 Coal Sector","Lights/Sound/ACTIVE BRAKING/*Horn 1/*Horn 3/*Clag/TAIL LIGHTS/*Notch Up/*Prepare for Off/*Guards Whistle/Spirax Valves/*Brake Release/Cab Lights/Flange Squeal 1/Flange Squeal 2/*Revving Engine/Compressor/*Clag 2/*Horn 2/MUTE/SHUNT")
ROSTER(3751,"37501 BSC Blue","Lights/Sound/ACTIVE BRAKING/*Horn 1/*Horn 5/*Clag/TAIL LIGHTS/*Notch Up/*Brake Release/*Dockside/Rail Echo/*Air Gush/Cab Lights/Announcement/Flange Squeal/*Ignition Spin/*Crossing Barrier/*Clag 2/*Horn 3/MUTE/SHUNT")
ROSTER(3752,"37502 Railfreight","Lights/Sound/ACTIVE BRAKING/*Horn 1/*Horn 3/*Clag/TAIL LIGHTS/*Notch Up/*Prepare for Off/*Guard’s Whistle/Spirax/*Brake Release///Squeal 1/Squeal 2/*Rev Up/Compressor/*Clag 2/*Horn 2/MUTE/SHUNT")
ROSTER(4011,"D211 BR Green","Lights/Sound/ACTIVE BRAKING/*Horn 1/*Horn 2/*Air Gush/TAIL LIGHTS/*Notch Up/*Brake Release/*Guard’s Whistle/Clag/Compressor///Announcement/Squeal 1/Rail Clack/Squeal 2/*Horn 3/*Horn 4/MUTE/SHUNT")
ROSTER(4653,"46053 BR Blue","Lights/Sound/ACTIVE BRAKING/*Horn 1/*Horn 2/*Shhhh/TAIL LIGHTS/*Notch Up/*Brake Squeal/*Guard’s Whistle/Truck Squeal/Compressor///Announcement/Flange Squeal/Coach Rattle/*Air Escape/*Announcement 2/*Horn 3/MUTE/SHUNT")
ROSTER(4709,"47209 Speedlink","Lights/Sound/ACTIVE BRAKING/*Horn 1/*Horn 2/*Clag/TAIL LIGHTS/*Notch Up/Clag + Spirax/*Guard’s Whistle/Cooler Fan/Spirax/HEADLIGHT/*Announcement/Flange Squeal/Clag 3/*Coupling Up/Compressor 2/*Horn 3/MUTE/SHUNT")
ROSTER(4712,"47612 InterCity","Lights/Sound/ACTIVE BRAKING/*Horn 1/*Horn 2/*Clag/TAIL LIGHTS/*Notch Up/Clag + Spirax/*Guard’s Whistle/Cooler Fan/Spirax/HEADLIGHT/*Announcement/Flange Squeal/Clag 3/*Coupling Up/Compressor 2/*Horn 3/MUTE/SHUNT")
ROSTER(4718,"47018 Railfreight","Lights/Sound/ACTIVE BRAKING/*Horn 1/*Horn 2/*Clag/TAIL LIGHTS/*Notch Up/Clag + Spirax/*Guard’s Whistle/Cooler Fan/Spirax/HEADLIGHT/*Announcement/Flange Squeal/Clag 3/*Coupling Up/Compressor 2/*Horn 3/MUTE/SHUNT")
ROSTER(4735,"47035 Blue","Lights/Sound/ACTIVE BRAKING/*Horn 1/*Horn 2/*Clag/TAIL LIGHTS/*Notch Up/Clag + Spirax/*Guard’s Whistle/Cooler Fan/Spirax/HEADLIGHT/*Announcement/Flange Squeal/Clag 3/*Coupling Up/Compressor 2/*Horn 3/MUTE/SHUNT")
ROSTER(4745,"47745 RES","Lights/Sound/Brake Sounds/*Horn 1/*Horn 2/Heavy Load/Coasting/Max Revs/Couplers/Flange Squeal/Cooler Fan/*Air Dump/Guard’s Whistle/Cab Light #1/Cab Light #2/Uncoupling Shuffle/*AWS Horn/*AWS Bell/Sound Fade/MUTE/Lights Off #1")
ROSTER(4752,"47522 Parcels","Lights/Sound/ACTIVE BRAKING/*Horn 1/*Horn 2/*Clag/TAIL LIGHTS/*Notch Up/Clag + Spirax/*Guard’s Whistle/Cooler Fan/Spirax/HEADLIGHT/*Announcement/Flange Squeal/Clag 3/*Coupling Up/Compressor 2/*Horn 3/MUTE/SHUNT")
ROSTER(4774,"47474 GPO Red","Lights/Sound/ACTIVE BRAKING/*Horn 1/*Horn 2/*Clag/TAIL LIGHTS/*Notch Up/Clag + Spirax/*Guard’s Whistle/Cooler Fan/Spirax/HEADLIGHT/*Announcement/Flange Squeal/Clag 3/*Coupling Up/Compressor 2/*Horn 3/MUTE/SHUNT")
ROSTER(4798,"47798 Royal","Lights/Sound/Brake Sounds/*Horn 1/*Horn 2/Heavy Load/Coasting/Max Revs/Couplers/Flange Squeal/Cooler Fan/*Air Dump/Guard’s Whistle/Cab Light #1/Cab Light #2/Uncoupling Shuffle/*AWS Horn/*AWS Bell/Sound Fade/MUTE/Lights Off #1")
ROSTER(5007,"50007 GWR","Lights/Sound/*Horn 1/*Horn 2/*Buffering Up/*Carriage Doors/*Cab Door/*Brakes/SPEED LOCK/Flange Squeal/*Guard’s Whistle/*Coupling Up/SOUND FADE/Cab Light #1/Cab Light #2/*Horn High/*Horn Low/Compressor/Cooler Fan/Lights #2 End/Lights #1 End")
ROSTER(5215,"D1025 Champion","Lights/Sound/*Horn 1/*Horn 2/*Horn 3/*Buffering Up/*Coupling Up/*Guard’s Whistle/*Carriage Doors/Flange Squeal/Wheel Groan/*Cylinder Clear/SHUNT/INERTIA/TAIL LIGHTS #1/TAIL LIGHTS #2/Compressor/DRIVE HOLD/SOUND FADE")
ROSTER(5500,"DELTIC","Lights/Sound/*Horn Double/*Horn Single/*Brake Release/Tail Lights #1/Tail Lights #2/*Cab Door/*Guard’s Whistle/*Horn Short/Flange Squeal/Compressor/Spirax/Wheel Clack/Thrash/IDLE/*Horn Short 2/Coach Rattle")
ROSTER(5502,"55002 Green","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Horn 3/TAIL LIGHTS/*Notch Up/*Brake Release/*Guard’s Whistle/*Set Off/Compressor/*Rev Up/*Announcement/Flange Squeal/Rail Clack/*Brakes Apply/*Failed Start/*Horn 4/MUTE/SHUNT")
ROSTER(5515,"55015 Blue","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Rev Up///*Notch Up/*Brake Release/*Guard’s Whistle/*Set Off/Compressor///Announcement/Flange Squeal/Rail Clack/*Brakes Apply/*Failed Start/*Horn 3/MUTE/SHUNT")
ROSTER(5605,"56005 Railfreight","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Set Off///Notch Up/*Brake Release/*Guard’s Whistle/*Cab Beeps/Rail Echo///*Announcement/Squeal 1/Squeal 2/*Comms Bell/*Horn 3/*Horn 4/MUTE/SHUNT")
ROSTER(5619,"56019 Railfreight","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Set Off/Tail Lights/Notch Up/*Brake Release/*Guard’s Whistle/*Cab Beeps/Rail Echo///*Announcement/Squeal 1/Squeal 2/*Comms Bell/*Horn 3/*Horn 4/MUTE/SHUNT")
ROSTER(5690,"56090 Large Logo","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Set Off///Notch Up/*Brake Release/*Guard’s Whistle/*Cab Beeps/Rail Echo///*Announcement/Squeal 1/Squeal 2/*Comms Bell/*Horn 3/*Horn 4/MUTE/SHUNT")
ROSTER(5708,"57008 Freightliner","Lights/Sound/*Horn//////*Horn 2/*Horn 3/*Horn 4/MUTE/*Horn 7/*Brake Release/Air Change/Squeal 1/Squeal 2/*Announce 1/*Announce 2/*Guard’s Whistle/*AWS Bell/*Air Release/*Horn 6/SOUND FADE")
ROSTER(5736,"57306 Virgin","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Air Charge/TAIL LIGHTS/*Notch Up/*Brake Release/*Guard’s Whistle/*Crossing Bell/*Brakes/HEADLIGHT/*Announcement/*TB Count/TB Theme/*Horn 3/*Horn 4/*Horn 5/MUTE/SHUNT")
ROSTER(5803,"58003 Railfreight","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Set Off///Notch Up/*Brake Release/*Guard’s Whistle/*Cab Beeps/Rail Echo///*Announcement/Squeal 1/Squeal 2/*Comms Bell/*Horn 3/*Horn 4/MUTE/SHUNT")
ROSTER(5817,"58017 Coal","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Set Off///Notch Up/*Brake Release/*Guard’s Whistle/*Cab Beeps/Rail Echo///*Announcement/Squeal 1/Squeal 2/*Comms Bell/*Horn 3/*Horn 4/MUTE/SHUNT")
ROSTER(5901,"59001 Yeoman","Lights-Day/Sound/*Horn Dual/Tail Lights OFF/Cab Lights/*Brakes/Lights-Yard 1/Park Lights/DRIVE LOCK/Flange Squeal/Lights-Nite/Lights-Yard 2/*Horn Hi/*Horn Lo/*Buffer Up/Spirax/*Door Slam/Compressor/*Detonators/*Radar Hiss/*Guard’s Whistle")
ROSTER(5914,"59104 ARC","Lights-Day/Sound/*Horn Dual/Tail Lights OFF/Cab Lights/*Brakes/Lights-Yard 1/Park Lights/DRIVE LOCK/Flange Squeal/Lights-Nite/Lights-Yard 2/*Horn Hi/*Horn Lo/*Buffer Up/Spirax/*Door Slam/Compressor/*Detonators/*Radar Hiss/*Guard’s Whistle")
ROSTER(5924,"59204 NPower","Lights-Day/Sound/*Horn Hi-Lo/*Horn Lo-Hi/*Buffer Up/*Carriage Doors/*Cab Door/Brakes/DRIVE LOCK/Flange Squeal/*Guard’s Whistle/*Coupling/FADE/Cab Lite #2/Cab Lite #1/*Horn Hi/*Horn Lo/Pump/*Horn Medium/Lights #1/Lights #2")
ROSTER(6001,"60001 Grey","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Rev Up/TAIL LITES/Notch Up/*Brake Release/*Guard’s Whistle/Rail Echo/Compressor///*Announcement/Squeal 1/Squeal 2/*Doors/*Horn 3/*Horn 4/MUTE/SHUNT")
ROSTER(6006,"60006 BSC Blue","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Rev Up/TAIL LITES/Notch Up/*Brake Release/*Guard’s Whistle/Rail Echo/Compressor///*Announcement/Squeal 1/Squeal 2/*Doors/*Horn 3/*Horn 4/MUTE/SHUNT")
ROSTER(6609,"66209 EWS","Lights/Sound/*BRAKE/*Horn 1/*Horn 2/Light Engine/Idle/Speed Up/*Air Release/Flange Squeal/Tail Lites #2/*Control Air/Spirax/*Horn Triple/Pre-Start/Fan/*Horns/*Guard’s Whistle/*Doors/MUTE/Tail Lites #1")
ROSTER(6646,"66546 Freightliner","Lights/Sound/*BRAKE/*Horn 1/*Horn 2/Light Engine/Idle/Speed Up/*Air Release/Flange Squeal/Tail Lites/*Control Air/Spirax/*Horn Triple/Pre-Start/Fan/*Horns/*Guard’s Whistle/*Doors/MUTE/Roof Lites")
ROSTER(6819,"68019 TPE","Lights/Sound/*BRAKE/*Horn Hi/*Horn Lo//*Buffering/*Brakes/*Door Slam/Compressor/DRIVE LOCK/Flange Squeal/*Whistle/*Buzzer/Fan/*Sanders/Cab Lite #1/Cab Lite #2/Coach Squeal/StartUp/*Detonators1/Lites #2/Lites #1")
ROSTER(1082,"Class 108 Blue-Grey","Lights/Sound/*Horn High-Low/*Horn Low-High/*Horn Toot/LIGHT LOAD/Engine Cruise/Flange Squeal/*Handbrake/*Air Drain/*Guard Whistle/*Buzzer Single/*Buzzer Double/*Window Open/*Door Open/*Doors Slam/*Droplight Open/Wipers/MUTE/Boost Engine/*Ilkley Moor")
//ROSTER(1083,"Class 108 Blue","Lights/Sound/*Horn High-Low/*Horn Low-High/*Horn Toot/LIGHT LOAD/Engine Cruise/Flange Squeal/*Handbrake/*Air Drain/*Guard Whistle/*Buzzer Single/*Buzzer Double/*Window Open/*Door Open/*Doors Slam/*Droplight Open/Wipers/MUTE/Boost Engine/*Ilkley Moor")
ROSTER(1084,"Class 108 White-Blue","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Rev Up//*Low Beam/*Brake Release/*Guard Whistle/*Brakes/*Horn 3//*Announcement/Flange Squeal/Clickety Clack/*Cab Door/*Cab Lever/*Horn 4/MUTE/SHUNT")
ROSTER(1220,"Class 122 Blue RLV","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Rev Up//*Low Beam/*Brake Release/*Guard Whistle/*Brakes/*Horn 3//*Announcement/Flange Squeal/Clickety Clack/*Cab Door/*Cab Lever/*Horn 4/MUTE/SHUNT")
ROSTER(1281,"Class 128 Parcels","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Rev Up//*Low Beam/*Brake Release/*Guard Whistle/*Horn 3/*Sliding Doors//*Cab Lever/Flange Squeal/Clickety Clack/*Cab Door/*Horn 4/*Horn 5/MUTE/SHUNT")
ROSTER(1421,"Pacer Provincial","Lights/Sound/*Horn High/*Horn Low/*Doors/*Brakes/*Drivers Door/Compressor/*Toilet Flush/Flange Squeal/*Guard Whistle/*Buzzer/AirCon/*Coupling/*Uncoupling//*Announcement 1/*Announcement 2/*DETONATORS ")
ROSTER(1422,"Pacer Northern Spirit","Lights/Sound/*Horn High/*Horn Low/*Doors/*Brakes/*Drivers Door/Compressor/*Toilet Flush/Flange Squeal/*Guard Whistle/*Buzzer/AirCon/*Coupling/*Uncoupling//*Announcement 1/*Announcement 2/*DETONATORS ")
ROSTER(1501,"Class 150 Provincial","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Rev Up//Notch Up/*Brake Release/*Guard Whistle/Compressor/*Air Release//*Announcement/Flange Squeal/*Buzzer/*Doors//*Horn 3/*Horn Doppler/MUTE/SHUNT")
ROSTER(1502,"Class 150 Regional","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Rev Up//Notch Up/*Brake Release/*Guard Whistle/Compressor/*Air Release//*Announcement/Flange Squeal/*Buzzer/*Doors//*Horn 3/*Horn Doppler/MUTE/SHUNT")
ROSTER(1561,"Class 156 Regional","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Rev Up//Notch Up/*Brake Release/*Guard Whistle/*Short Move Off/Air Cylinders//*Announcement/Flange Squeal/*Rev Up2/*Doors/*Brakes/*Horn 3/MUTE/SHUNT")
ROSTER(1562,"Class 156 Northern Spirit","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Rev Up//Notch Up/*Brake Release/*Guard Whistle/*Short Move Off/Air Cylinders//*Announcement/Flange Squeal/*Rev Up2/*Doors/*Brakes/*Horn 3/MUTE/SHUNT")
ROSTER(1581,"Class 158 East Midlands","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Rev Up//Notch Up/*Brake Release/*Guard Whistle/*Short Move Off/Air Cylinders//*Announcement/Flange Squeal/*Rev Up2/*Doors/*Brakes/*Horn 3/MUTE SOUNDS/SHUNTING MODE")
ROSTER(1582,"Class 158 Regional","Lights/Sound/*Brake/*Horn Single/*Horn Double/LIGHT LOAD/Engine Idling/Flange Squeal/DOORS/*Despatch Whistle/*Buzzer Single/*Buzzer Double/Engine Rev Up/Aircon/Wipers/Doors 2/SOUNDS FADE/Lights Off Car A/Lights Off Car B/Station Sounds/*RETB Test")
ROSTER(2211,"Voyager 5 Car","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Pump Thrash//*Notch Up/*Air Escape/*Guards Whistle/*Announcement/Compressor//*Announcement 2/Flange Squeal/*Horn 3/Knocking/*Horn 4/*Horn 5/MUTE/SHUNT")
ROSTER(2510,"Midland Pullman","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Comms Buzzer//*Notch Up/*Brake Release/*Guards Whistle/*Set Off Flange/*Coupling Up//*Announcement/Flange Squeal/Clickety Clack/*Doors Closing/*Coupling Up 2/*Horn 3/MUTE/SHUNT")
ROSTER(2520,"HST Prototype","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Clag//*Notch Up/*Brake Release/*Guards Whistle/*Crossing Barrier/Compressor//*Announcement/Flange Squeal 1/Flange Squeal 2/*Doors Closing/*Horn 4/*Horn 5/MUTE/SHUNT")
ROSTER(2531,"HST Blue Grey","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Clag//*Notch Up/*Brake Release/*Guards Whistle/*Crossing Barrier/Compressor//*Announcement/Flange Squeal 1/Flange Squeal 2/*Doors Closing/*Horn 4/*Horn 5/MUTE/SHUNT")
ROSTER(2532,"HST Executive","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Clag//*Notch Up/*Brake Release/*Guards Whistle/*Crossing Barrier/Compressor//*Announcement/Flange Squeal 1/Flange Squeal 2/*Doors Closing/*Horn 4/*Horn 5/MUTE/SHUNT")
ROSTER(2533,"HST Swallow","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Clag//*Notch Up/*Brake Release/*Guards Whistle/*Crossing Barrier/Compressor//*Announcement/Flange Squeal 1/Flange Squeal 2/*Doors Closing/*Horn 4/*Horn 5/MUTE/SHUNT")
ROSTER(2534,"HST Virgin","Lights/Sound/ACTIVE BRAKE/*Horn 1/*Horn 2/*Clag//*Notch Up/*Brake Release/*Guards Whistle/*Crossing Barrier/Compressor//*Announcement/Flange Squeal 1/Flange Squeal 2/*Doors Closing/*Horn 4/*Horn 5/MUTE/SHUNT")
ROSTER(9522,"D9522 Green","//Sound/*BRAKE/*Horn 1/*Horn 2/Light Engine/Idle/SPEED LOCK/Flange Squeal/*Guard’s Whistle/*Buffer Up/*Couple Up/Compressor/Sanders/HANDBRAKE/Pump/Doors/SOUND FADE/Detonators/*Vocal 1/*Vocal 2")
ROSTER(9901,"THOMAS","//Sounds/ACTIVE BRAKE/*Whistle 1/*Whistle 2/Chuff Select/Coal Shovelling/*Thomas Tune/*Clank and Hiss/*Guard Whistle/Injector/*It’s Thomas/*Hello Thomas/*That Wasn’t Funny/*Announcement/Coach Rattle/*Ease Away/*Coupling Up/*Cinders and Ashes/*Cab Clanks/SHUNT")
ROSTER(9906,"PERCY","//Sounds/ACTIVE BRAKE/*Whistle 1/*Whistle 2/Chuff Select/Coal Shovelling/*Thomas Tune/*Hurry Up Slowcoach/*Guard Whistle/Injector/*Cab Clanks/*Out of my Way/*Bust my Boiler/*Cinders and Ashes/Blower/*Water Filling/*Water Hatch/*Whistle 3/*Buffer Up/SHUNT")
ROSTER(9907,"TOBY","//Sounds/ACTIVE BRAKE/*Whistle 1/*Whistle 2/Blower/Coal Shovelling/*Thomas Tune/*Toby Tune 1/*Guard Whistle/Steam Release/*Comms Bell/*Toby Tune 2/Westinghouse Pump/Flange Squeal/Coach Rattle/*Doors Closing/Drains and Water/*Whistle 3/*Doors Slam/SHUNT")






